### ISSUE TITLE
documentation: ChannelSetup()

### ISSUE THREAD

**Issue by dave-enyart** [ucd-squidlab/AD7734Lib#1]
I'd like to help with library if possible.
I'm trying to use it in a project I'm working on and I'm not sure if I'm using it correctly. 
It looks like ChannelSetup -> flags is setting the channel registers. Is this correct?

**Comment by josephhd** [comment]
There are a few channel registers. The ChannelSetup function is used to set the Channel Setup Registers. See page 19 of the [data sheet](https://www.analog.com/media/en/technical-documentation/data-sheets/AD7734.pdf). The flags can be used to set the Stat OPT, ENABLE, RNG-RNG0 bits.

**Comment by dave-enyart** [comment]
did you have a sample .ino to use a guide

**Comment by josephhd** [comment]
Unfortunately, I do not have a sample .ino that uses ChannelSetup. However, see this [repo](https://github.com/ucd-squidlab/DAQ). An example of how this library is being used is in DAQ.ino. 

Since I don't have one on hand, I'll make one up here. 

Suppose I want to set the nominal input voltage range to be +-5V. I would use the following options in the flags (again see pg. 19 of the AD7734 data sheet). 
`
int flags = PN_5;
` 

If I wanted to setup the ADC to input 0 to 5V and have the channel be enabled for continuous conversion, I would use these flags:
`
int flags = (1 << 3) | P_05;
`

In both cases, if I were setting the channel A setup register, the function call would look like this:
`
ChannelSetup(ADC_A, flags);
`

**Comment by dave-enyart** [comment]
Seeing that repo helps alot, i couldn't quite figure out the order of operations for config, set, and read.
